// <copyright file="IConfiguration.cs" company="APIMatic">
// SwaggerPetstoreOpenAPI310.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using SwaggerPetstoreOpenAPI310.Standard.Authentication;

namespace SwaggerPetstoreOpenAPI310.Standard
{
    /// <summary>
    /// IConfiguration.
    /// </summary>
    public interface IConfiguration
    {
        /// <summary>
        /// Gets Current API environment.
        /// </summary>
        Environment Environment { get; }

        /// <summary>
        /// Gets the credentials to use with PetstoreAuth.
        /// </summary>
        IPetstoreAuthCredentials PetstoreAuthCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with PetstoreAuth.
        /// </summary>
        PetstoreAuthModel PetstoreAuthModel { get; }

        /// <summary>
        /// Gets the credentials to use with ApiKey.
        /// </summary>
        IApiKeyCredentials ApiKeyCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with ApiKey.
        /// </summary>
        ApiKeyModel ApiKeyModel { get; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        string GetBaseUri(Server alias = Server.Default);
    }
}