// <copyright file="Server.cs" company="APIMatic">
// SwaggerPetstoreOpenAPI310.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace SwaggerPetstoreOpenAPI310.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// Default.
        /// </summary>
        Default,

        /// <summary>
        /// AuthServer.
        /// </summary>
        AuthServer,
    }
}
