// <copyright file="SwaggerPetstoreOpenAPI310Client.cs" company="APIMatic">
// SwaggerPetstoreOpenAPI310.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using Microsoft.Extensions.Configuration;
using SwaggerPetstoreOpenAPI310.Standard.Authentication;
using SwaggerPetstoreOpenAPI310.Standard.Controllers;
using SwaggerPetstoreOpenAPI310.Standard.Http.Client;
using System;
using System.Collections.Generic;

namespace SwaggerPetstoreOpenAPI310.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class SwaggerPetstoreOpenAPI310Client : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://petstore3.swagger.io/api/v3" },
                    { Server.AuthServer, "https://petstore3.swagger.io/oauth" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private const string userAgent = "APIMATIC 3.0";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<PetController> pet;
        private readonly Lazy<StoreController> store;
        private readonly Lazy<UserController> user;

        private SwaggerPetstoreOpenAPI310Client(
            Environment environment,
            PetstoreAuthModel petstoreAuthModel,
            ApiKeyModel apiKeyModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            PetstoreAuthModel = petstoreAuthModel;
            var petstoreAuthManager = new PetstoreAuthManager(petstoreAuthModel,
                () => globalConfiguration);
            ApiKeyModel = apiKeyModel;
            var apiKeyManager = new ApiKeyManager(apiKeyModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"petstore_auth", petstoreAuthManager},
                    {"api_key", apiKeyManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .UserAgent(userAgent)
                .Build();
            PetstoreAuthCredentials = petstoreAuthManager;
            ApiKeyCredentials = apiKeyManager;

            this.pet = new Lazy<PetController>(
                () => new PetController(globalConfiguration));
            this.store = new Lazy<StoreController>(
                () => new StoreController(globalConfiguration));
            this.user = new Lazy<UserController>(
                () => new UserController(globalConfiguration));
        }

        /// <summary>
        /// Gets PetController controller.
        /// </summary>
        public PetController PetController => this.pet.Value;

        /// <summary>
        /// Gets StoreController controller.
        /// </summary>
        public StoreController StoreController => this.store.Value;

        /// <summary>
        /// Gets UserController controller.
        /// </summary>
        public UserController UserController => this.user.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with PetstoreAuth.
        /// </summary>
        public IPetstoreAuthCredentials PetstoreAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with PetstoreAuth.
        /// </summary>
        public PetstoreAuthModel PetstoreAuthModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with ApiKey.
        /// </summary>
        public IApiKeyCredentials ApiKeyCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ApiKey.
        /// </summary>
        public ApiKeyModel ApiKeyModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SwaggerPetstoreOpenAPI310Client using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .HttpClientConfig(config => config.Build());

            if (PetstoreAuthModel != null)
            {
                builder.PetstoreAuthCredentials(PetstoreAuthModel.ToBuilder().Build());
            }

            if (ApiKeyModel != null)
            {
                builder.ApiKeyCredentials(ApiKeyModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SwaggerPetstoreOpenAPI310Client.</returns>
        internal static SwaggerPetstoreOpenAPI310Client CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_310_STANDARD_ENVIRONMENT");
            string oAuthClientId = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_310_STANDARD_O_AUTH_CLIENT_ID");
            string oAuthRedirectUri = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_310_STANDARD_O_AUTH_REDIRECT_URI");
            string apiKey = System.Environment.GetEnvironmentVariable("SWAGGER_PETSTORE_OPEN_API_310_STANDARD_API_KEY");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oAuthClientId != null && oAuthRedirectUri != null)
            {
                builder.PetstoreAuthCredentials(new PetstoreAuthModel
                .Builder(oAuthClientId, oAuthRedirectUri)
                .Build());
            }

            if (apiKey != null)
            {
                builder.ApiKeyCredentials(new ApiKeyModel
                .Builder(apiKey)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SwaggerPetstoreOpenAPI310Client.</returns>
        public static SwaggerPetstoreOpenAPI310Client FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SwaggerPetstoreOpenAPI310.Standard.Environment.Production;
            private PetstoreAuthModel _petstoreAuthModel = new PetstoreAuthModel();
            private ApiKeyModel _apiKeyModel = new ApiKeyModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;

            /// <summary>
            /// Sets credentials for PetstoreAuth.
            /// </summary>
            /// <param name="petstoreAuthModel">PetstoreAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder PetstoreAuthCredentials(PetstoreAuthModel petstoreAuthModel)
            {
                _petstoreAuthModel = petstoreAuthModel ??
                    throw new ArgumentNullException(nameof(petstoreAuthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for ApiKey.
            /// </summary>
            /// <param name="apiKeyModel">ApiKeyModel.</param>
            /// <returns>Builder.</returns>
            public Builder ApiKeyCredentials(ApiKeyModel apiKeyModel)
            {
                _apiKeyModel = apiKeyModel ??
                    throw new ArgumentNullException(nameof(apiKeyModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SwaggerPetstoreOpenAPI310Client using the values provided for the builder.
            /// </summary>
            /// <returns>SwaggerPetstoreOpenAPI310Client.</returns>
            public SwaggerPetstoreOpenAPI310Client Build()
            {
                if (_petstoreAuthModel.OAuthClientId == null || _petstoreAuthModel.OAuthRedirectUri == null)
                {
                    _petstoreAuthModel = null;
                }
                if (_apiKeyModel.ApiKey == null)
                {
                    _apiKeyModel = null;
                }
                return new SwaggerPetstoreOpenAPI310Client(
                    _environment,
                    _petstoreAuthModel,
                    _apiKeyModel,
                    _httpCallback,
                    _httpClientConfig.Build());
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SwaggerPetstoreOpenAPI310ClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.PetstoreAuthCredentials != null)
                    builder.PetstoreAuthCredentials(PetstoreAuthModel.FromOptions(options.PetstoreAuthCredentials));
                if (options.ApiKeyCredentials != null)
                    builder.ApiKeyCredentials(ApiKeyModel.FromOptions(options.ApiKeyCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                return builder;
            }
        }

        public class SwaggerPetstoreOpenAPI310ClientOptions
        {
            public Environment? Environment { get; set; }
            public PetstoreAuthModelOptions PetstoreAuthCredentials { get; set; }
            public ApiKeyModelOptions ApiKeyCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
        }
    }
}
