<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.8" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
        <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.8" />
        <PackageVersion Include="Microsoft.Bcl.TimeProvider" Version="10.0.8" />
        <PackageVersion Include="Polly" Version="8.6.5" />
        <PackageVersion Include="PolySharp" Version="1.15.0" />
        <PackageVersion Include="System.Net.Http.Json" Version="10.0.8" />
        <PackageVersion Include="System.Net.ServerSentEvents" Version="10.0.8" />
        <PackageVersion Include="System.Text.Json" Version="10.0.8" />
    </ItemGroup>

</Project>