// <copyright file="ControllerTestBase.cs" company="APIMatic">
// SwaggerPetstoreOpenAPI310.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using SwaggerPetstoreOpenAPI310.Standard;
using SwaggerPetstoreOpenAPI310.Standard.Authentication;
using SwaggerPetstoreOpenAPI310.Standard.Http.Client;
using SwaggerPetstoreOpenAPI310.Standard.Models;

namespace SwaggerPetstoreOpenAPI310.Tests
{
    /// <summary>
    /// ControllerTestBase Class.
    /// </summary>
    [TestFixture]
    public class ControllerTestBase
    {
        /// <summary>
        /// Assert precision.
        /// </summary>
        protected const double AssertPrecision = 0.1;

        /// <summary>
        /// Gets HttpCallBackHandler.
        /// </summary>
        internal HttpCallback HttpCallBack { get; private set; } = new HttpCallback();

        /// <summary>
        /// Gets SwaggerPetstoreOpenAPI310Client Client.
        /// </summary>
        protected SwaggerPetstoreOpenAPI310Client Client { get; private set; }

        /// <summary>
        /// Set up the client.
        /// </summary>
        [OneTimeSetUp]
        public void SetUp()
        {
            SwaggerPetstoreOpenAPI310Client config = SwaggerPetstoreOpenAPI310Client.CreateFromEnvironment();
            this.Client = config.ToBuilder()
                .HttpCallback(HttpCallBack)
                .Build();
        }
    }
}