// <copyright file="OrderStatusEnum.cs" company="APIMatic">
// SwaggerPetstoreOpenAPI310.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace SwaggerPetstoreOpenAPI310.Standard.Models
{
    /// <summary>
    /// OrderStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    [XmlRoot("OrderStatus")]
    public enum OrderStatusEnum
    {
        /// <summary>
        /// Placed.
        /// </summary>
        [XmlEnum("placed")]
        [EnumMember(Value = "placed")]
        Placed,

        /// <summary>
        /// Approved.
        /// </summary>
        [XmlEnum("approved")]
        [EnumMember(Value = "approved")]
        Approved,

        /// <summary>
        /// Delivered.
        /// </summary>
        [XmlEnum("delivered")]
        [EnumMember(Value = "delivered")]
        Delivered
    }
}